FROM golang:1.23.1-alpine AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod tidy

COPY . .
RUN go build -o worker ./cmd/worker/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /src/worker .

CMD ["./worker"]