apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: [ 'sh', '-c', 'until nc -z mysql-db 3306; do echo waiting for mysql; sleep 2; done;' ]
      containers:
        - name: api
          image: conch2147/url-shortener:latest
          env:
            - name: BASE_URL
              value: "http://localhost:30080"
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          ports:
            - containerPort: 8080