apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  MYSQL_USER: YWRtaW4=       # base64(admin)
  MYSQL_PASSWORD: YWRtaW4=   # base64(admin)
  DB_USER: YWRtaW4=
  DB_PASSWORD: YWRtaW4=